 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/professional_data", type: :request do
  # ProfessionalData. As you add validations to ProfessionalData, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProfessionalData.create! valid_attributes
      get professional_data_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      professional_datum = ProfessionalData.create! valid_attributes
      get professional_datum_url(professional_datum)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_professional_datum_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      professional_datum = ProfessionalData.create! valid_attributes
      get edit_professional_datum_url(professional_datum)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProfessionalData" do
        expect {
          post professional_data_url, params: { professional_datum: valid_attributes }
        }.to change(ProfessionalData, :count).by(1)
      end

      it "redirects to the created professional_datum" do
        post professional_data_url, params: { professional_datum: valid_attributes }
        expect(response).to redirect_to(professional_datum_url(ProfessionalData.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProfessionalData" do
        expect {
          post professional_data_url, params: { professional_datum: invalid_attributes }
        }.to change(ProfessionalData, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post professional_data_url, params: { professional_datum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested professional_datum" do
        professional_datum = ProfessionalData.create! valid_attributes
        patch professional_datum_url(professional_datum), params: { professional_datum: new_attributes }
        professional_datum.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the professional_datum" do
        professional_datum = ProfessionalData.create! valid_attributes
        patch professional_datum_url(professional_datum), params: { professional_datum: new_attributes }
        professional_datum.reload
        expect(response).to redirect_to(professional_datum_url(professional_datum))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        professional_datum = ProfessionalData.create! valid_attributes
        patch professional_datum_url(professional_datum), params: { professional_datum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested professional_datum" do
      professional_datum = ProfessionalData.create! valid_attributes
      expect {
        delete professional_datum_url(professional_datum)
      }.to change(ProfessionalData, :count).by(-1)
    end

    it "redirects to the professional_data list" do
      professional_datum = ProfessionalData.create! valid_attributes
      delete professional_datum_url(professional_datum)
      expect(response).to redirect_to(professional_data_url)
    end
  end
end
